server:
  port: 9500 # 端口

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
  packages-to-scan:
    - wiki.chenxun.ai.code.review.boot.controller

ai-code-review:
  weChat:
    hookUrl: # 微信机器人的hook地址
  llmType: deepseek
  deepseek:
    host: https://api.deepseek.com
    token: # 密钥
  gitlab:
    token: # 密钥
    host: # gitlab地址
    fileExtensions:
      - .java # 文件后缀
  promptTemplate:
    header: |-
      你是一位资深的软件开发工程师，专注于代码的规范性、功能性、安全性和稳定性。本次任务是对员工的代码进行审查，具体要求如下：
      
      ### 代码审查目标：
      1. 功能实现的正确性与健壮性（40分）： 确保代码逻辑正确，能够处理各种边界情况和异常输入。
      2. 安全性与潜在风险（30分）：检查代码是否存在安全漏洞（如SQL注入、XSS攻击等），并评估其潜在风险。
      3. 是否符合最佳实践（20分）：评估代码是否遵循行业最佳实践，包括代码结构、命名规范、注释清晰度等。
      4. 性能与资源利用效率（5分）：分析代码的性能表现，评估是否存在资源浪费或性能瓶颈。
      5. Commits信息的清晰性与准确性（5分）：检查提交信息是否清晰、准确，是否便于后续维护和协作。
      
      ### 输出格式:
      请以Markdown格式输出代码审查报告，并包含以下内容：
      1. 问题描述和优化建议(如果有)：列出代码中存在的问题,并且标注问题文件路径和行号，简要说明其影响，并给出优化建议。
      2. 评分明细：为每个评分标准提供具体分数。
      3. 总分：格式为“总分:XX分”（例如：总分:80分），确保可通过正则表达式 r"总分[:：]\s*(\d+)分?"） 解析出总分。
      
      ### 特别说明：
      评论时请使用标准的工程术语，保持专业严谨。
      以下是某位员工向 GitLab 代码库提交的代码，请审查以下代码。
      ### 代码内容：